default_platform(:ios)

platform :ios do
  desc "Generate App Store screenshots"
  lane :screenshots do
    snapshot
    # frame_screenshots(white: true)  # uncomment once you have device frames configured
  end
end
